### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by yurchor**
Thanks for reviewing this request.

### CODE REVIEW

**Comment by jwpi** [comment]
Nice work yurchor. Patches should be submitted to the mailing list for review:
<https://sourceware.org/ml/libc-alpha/2014-12/msg01002.html> 

Although, reviewing them here with the highlighted diffs is nice.

**Comment by yurchor** [comment]
Ok. There are some more typos ("typy", "--id s deprecated in"). If I manage how to configure git send-email for my email server I will send them. I'm just a translator, not a professional programmer. Sorry.

**Comment by jwpi** [comment]
Hello yurchor,
I wasn't suggesting that you should close this pull request.
Karel may except it without you sending it for review. I was
just letting you know that that is the normal way to submit a
patch.

**Comment by yurchor** [comment]
Sorry for misunderstanding.

**Comment by karelzak** [comment]
Applied manually from mailing list, thanks!

**Pull request closed without merging**
