### PR TITLE
travis: build util-linux on arm64, ppc64le and s390x

### PR DESCRIPTION
**Pull request by evverx**

### CODE REVIEW

**Comment by karelzak** [comment]
Oh, thanks for this -- it will help me for my work in Red Hat :-) It's always better to detect bugs in upstream than later in downstream.

**Comment by karelzak** [comment]
Oh, I have merged this on and it is marked as "draft" PR -- do you want to keep it? For me, it's an attractive feature.

**Comment by evverx** [comment]
I didn't mark it as ready for review because the "blkid/dm-err" test seems to be failing there with:
```
        blkid: DM error                       .../dev/mapper/control: mknod failed: Operation not permitted
Failure to communicate with kernel device-mapper driver.
Check that device-mapper is available in the kernel.
Incompatible libdevmapper 1.02.145 (2017-11-03) and kernel driver (unknown version).
Command failed
/dev/mapper/control: mknod failed: Operation not permitted
Failure to communicate with kernel device-mapper driver.
Check that device-mapper is available in the kernel.
Incompatible libdevmapper 1.02.145 (2017-11-03) and kernel driver (unknown version).
Command failed
diff-{{{
--- /dev/null	2020-05-31 18:07:01.916000000 +0000
+++ /home/travis/build/karelzak/util-linux/tests/output/blkid/dm-err.err	2020-07-02 21:41:39.657694161 +0000
@@ -0,0 +1 @@
+blkid: error: /dev/mapper/blkid-dm-err: No such file or directory
}}}-diff
 FAILED (blkid/dm-err)
```

Plus on s390x `LSan` isn't supported, which causes some tests to fail with
```
diff-{{{
--- /dev/null	2020-06-05 10:12:06.485646596 +0000
+++ /home/travis/build/karelzak/util-linux/tests/output/libfdisk/gpt-getattr.err	2020-07-02 20:15:21.831506995 +0000
@@ -0,0 +1,2 @@
+==72289==AddressSanitizer: detect_leaks is not supported on this platform.
+==72290==AddressSanitizer: detect_leaks is not supported on this platform.
}}}-diff
```

I'd revert this commit for now to make Travis CI green.

**Comment by evverx** [comment]
Also with https://github.com/karelzak/util-linux/issues/1091 merged, util-linux is failing to compile on s390x due to https://github.com/karelzak/util-linux/issues/1091.

**Comment by evverx** [comment]
@karelzak now that there are a lot of jobs that can be run in parallel could you turn on [auto cancellation](https://blog.travis-ci.com/2017-03-22-introducing-auto-cancellation) on Travis CI for branch builds and pull request builds?

**Comment by evverx** [comment]
The "blkid/dm-err" issue should be addressed in https://github.com/karelzak/util-linux/pull/1093.

**Comment by evverx** [comment]
The "LSan" issue was fixed in that PR as well. Once it's merged Travis CI will be green again.

**Comment by karelzak** [comment]
> @karelzak now that there are a lot of jobs that can be run in parallel could you turn on [auto cancellation](https://blog.travis-ci.com/2017-03-22-introducing-auto-cancellation) on Travis CI for branch builds and pull request builds?

@evverx There is already auto-cancel enabled for PR and repo branches.

**Comment by evverx** [comment]
Good to know. Thanks!

**Pull request merged**
