### PR TITLE
libfdisk: Fix C/H/S geometry code

### PR DESCRIPTION
**Pull request by pali**
This pull request contains different fixes for C/H/S geometry related code which is used by libfdisk and fdisk utility. Common mistake is that _number of disk heads_ is incorrectly exchanged with _head_ number in C/H/S partition offset. Same for _sectors per disk tracks_ and _sector_ number in C/H/S partition offset.

Somebody would say that C/H/S based geometry is dead for a long time... but it is not truth. Even in 2021 are in use (relatively new!) systems which require aligning FAT partitions to cylinders. So the best option for these systems is to use fdisk's _dos compatibility_ mode with manually specified `-H` and `-S` parameters when creating / modifying partitions in MBR table.

This pull request is just a _draft_ for now, please let me know what do you think about it. I guess that issues described and fixed in commits may affect / break tests as I think that nobody cared about C/H/S and tests for them for more than decade... plus C/H/S is stored in every MBR table. So any fixed C/H/S related code changes what is stored in C/H/S parts of MBR table.

### CODE REVIEW

**Comment by karelzak** [comment]
It would be nice to check and update our regression tests:
```
 $ sudo ./run.sh fdisk

-------------------- util-linux regression tests --------------------

                    For development purpose only.                    
                 Don't execute on production system!                 

       kernel: 5.12.12-300.fc34.x86_64           

      options: --srcdir=/home/projects/util-linux/util-linux/tests/.. \
               --builddir=/home/projects/util-linux/util-linux/tests/..

        fdisk: align 512/4K                   ... OK
        fdisk: align 512/4K +alignment_offset ... OK
        fdisk: align 512/4K +MD               ... OK
        fdisk: align 512/512                  ... OK
        fdisk: align 512/512 +topology        ... OK
        fdisk: nested BSD                     ... FAILED (fdisk/bsd)
        fdisk: GPT                            ... OK
        fdisk: gpt-resize                     ... OK
        fdisk: MBR - id                       ... OK
        fdisk: MBR - dos mode                 ... OK
        fdisk: MBR - non-dos mode             ...
                : empty-pt                    ... OK
                : 1st-primary                 ... OK
                : 1st-active                  ... OK
                : 1st-primary-recreate        ... FAILED (fdisk/mbr-nondos-mode-1st-primary-recreate)
                : 2nd-primary                 ... FAILED (fdisk/mbr-nondos-mode-2nd-primary)
                : extended                    ... FAILED (fdisk/mbr-nondos-mode-extended)
                : logical                     ... FAILED (fdisk/mbr-nondos-mode-logical)
                : logical-delete              ... FAILED (fdisk/mbr-nondos-mode-logical-delete)
                : logical-recreate            ... FAILED (fdisk/mbr-nondos-mode-logical-recreate)
                : 1st-primary-delete          ... FAILED (fdisk/mbr-nondos-mode-1st-primary-delete)
                : 1nd-primary-delete          ... OK
                : extended-delete             ... OK
                : first-sector-at-end         ... OK
           ... FAILED (7 from 13 sub-tests)
        fdisk: MBR - sort                     ... OK
        fdisk: invalid input tests            ... OK
        fdisk: sunlabel tests                 ... OK

---------------------------------------------------------------------
  2 tests of 14 FAILED
---------------------------------------------------------------------
```
The problem is usually a checksum change, for example:
```
--- /home/projects/util-linux/util-linux/tests/expected/fdisk/mbr-nondos-mode-1st-primary-recreate      2021-07-14 13:36:40.6267
+++ /home/projects/util-linux/util-linux/tests/output/fdisk/mbr-nondos-mode-1st-primary-recreate        2021-07-14 13:36:53.8006
@@ -1,5 +1,5 @@
 Re-create 1st primary partition
-a5543ee1e3d2cf79913a56bae893a0f0 mbr-nondos-mode.img
+e21e16b7452d82e2a2810a1de8c3db05 mbr-nondos-mode.img
 
 ---layout----------
 Disk <removed>: 20 MiB, 20971520 bytes, 40960 sectors
```

The changes are usually in non-dos mode stuff, so I guess it's triggered by 

 -  libfdisk: (dos) Fix setting CHS values when creating new partition
 -  libfdisk: (dos) Fix determining number of heads and sectors per track from MBR 

and all we need is to update the checksums only.

**Comment by pali** [comment]
> It would be nice to check and update our regression tests:

I know... And this pull request https://github.com/karelzak/util-linux/pull/1386 could help with it.

**Comment by karelzak** [comment]
> I know... And this pull request #1386 could help with it.

It does not update the checksums :-)

**Comment by pali** [comment]
I rebased pull request on top of master branch and here is detailed output of failed tests:
```
        fdisk: nested BSD                     ...
diff-{{{
--- /home/runner/work/util-linux/util-linux/tests/expected/fdisk/bsd_1_0.LE	2021-07-15 19:51:04.533586217 +0000
+++ /home/runner/work/util-linux/util-linux/tests/output/fdisk/bsd	2021-07-15 19:55:10.567688727 +0000
@@ -55,8 +55,8 @@
 00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 *
 000001b0  00 00 00 00 00 00 00 00  01 00 00 00 00 00 00 20  |............... |
-000001c0  21 00 83 41 01 00 00 08  00 00 00 08 00 00 00 04  |!..A............|
-000001d0  01 3e 83 13 41 36 00 10  00 00 00 40 00 00 00 00  |.>..A6.....@....|
+000001c0  21 00 83 41 01 00 00 08  00 00 00 08 00 00 00 41  |!..A...........A|
+000001d0  02 00 83 46 05 01 00 10  00 00 00 40 00 00 00 00  |...F.......@....|
 000001e0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 000001f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 55 aa  |..............U.|
 00000200  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
@@ -66,8 +66,8 @@
 00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 *
 000001b0  00 00 00 00 00 00 00 00  01 00 00 00 00 00 00 20  |............... |
-000001c0  21 00 83 41 01 00 00 08  00 00 00 08 00 00 00 04  |!..A............|
-000001d0  01 3e a5 13 41 36 00 10  00 00 00 40 00 00 00 00  |.>..A6.....@....|
+000001c0  21 00 83 41 01 00 00 08  00 00 00 08 00 00 00 41  |!..A...........A|
+000001d0  02 00 a5 46 05 01 00 10  00 00 00 40 00 00 00 00  |...F.......@....|
 000001e0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 000001f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 55 aa  |..............U.|
 00000200  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
@@ -84,15 +84,15 @@
 
 Device     Boot Start   End Sectors Id Type    Start-C/H/S End-C/H/S Attrs
 <removed>1       2048  4095    2048 83 Linux       0/32/33    0/65/1 
-<removed>2       4096 20479   16384 a5 FreeBSD      62/4/1  310/19/1 
+<removed>2       4096 20479   16384 a5 FreeBSD      0/65/2    1/70/5 
 -------------------
 
 Create default BSD
 00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 *
 000001b0  00 00 00 00 00 00 00 00  01 00 00 00 00 00 00 20  |............... |
-000001c0  21 00 83 41 01 00 00 08  00 00 00 08 00 00 00 04  |!..A............|
-000001d0  01 3e a5 13 41 36 00 10  00 00 00 40 00 00 00 00  |.>..A6.....@....|
+000001c0  21 00 83 41 01 00 00 08  00 00 00 08 00 00 00 41  |!..A...........A|
+000001d0  02 00 a5 46 05 01 00 10  00 00 00 40 00 00 00 00  |...F.......@....|
 000001e0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 000001f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 55 aa  |..............U.|
 00000200  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
@@ -144,8 +144,8 @@
 00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 *
 000001b0  00 00 00 00 00 00 00 00  01 00 00 00 00 00 00 20  |............... |
-000001c0  21 00 83 41 01 00 00 08  00 00 00 08 00 00 00 04  |!..A............|
-000001d0  01 3e a5 13 41 36 00 10  00 00 00 40 00 00 00 00  |.>..A6.....@....|
+000001c0  21 00 83 41 01 00 00 08  00 00 00 08 00 00 00 41  |!..A...........A|
+000001d0  02 00 a5 46 05 01 00 10  00 00 00 40 00 00 00 00  |...F.......@....|
 000001e0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 000001f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 55 aa  |..............U.|
 00000200  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
}}}-diff

 FAILED (fdisk/bsd)
        fdisk: GPT                            ... OK
        fdisk: gpt-resize                     ... OK
        fdisk: MBR - id                       ... OK
        fdisk: MBR - dos mode                 ... OK
        fdisk: MBR - non-dos mode             ...
                : empty-pt                    ... OK
                : 1st-primary                 ... OK
                : 1st-active                  ... OK
                : 1st-primary-recreate        ...
diff-{{{
--- /home/runner/work/util-linux/util-linux/tests/expected/fdisk/mbr-nondos-mode-1st-primary-recreate	2021-07-15 19:51:04.533586217 +0000
+++ /home/runner/work/util-linux/util-linux/tests/output/fdisk/mbr-nondos-mode-1st-primary-recreate	2021-07-15 19:55:13.895688727 +0000
@@ -1,5 +1,5 @@
 Re-create 1st primary partition
-a5543ee1e3d2cf79913a56bae893a0f0 mbr-nondos-mode.img
+e21e16b7452d82e2a2810a1de8c3db05 mbr-nondos-mode.img
 
 ---layout----------
 Disk <removed>: 20 MiB, 20971520 bytes, 40960 sectors
@@ -10,6 +10,6 @@
 Disk identifier: <removed>
 
 Device     Boot Start   End Sectors Id Type  Start-C/H/S End-C/H/S Attrs
-<removed>1       2048  8191    6144 83 Linux     7/107/1   31/34/2 
+<removed>1       2048  8191    6144 83 Linux     0/32/33   0/130/2 
 -------------------
 
}}}-diff

 FAILED (fdisk/mbr-nondos-mode-1st-primary-recreate)
                : 2nd-primary                 ...
diff-{{{
--- /home/runner/work/util-linux/util-linux/tests/expected/fdisk/mbr-nondos-mode-2nd-primary	2021-07-15 19:51:04.533586217 +0000
+++ /home/runner/work/util-linux/util-linux/tests/output/fdisk/mbr-nondos-mode-2nd-primary	2021-07-15 19:55:14.015688727 +0000
@@ -1,5 +1,5 @@
 Create 2nd primary partition
-9d31ee977e26e72ebce78e8e543cd4ce mbr-nondos-mode.img
+3e928fabe884f6d4906b4d9335e7c6a3 mbr-nondos-mode.img
 
 ---layout----------
 Disk <removed>: 20 MiB, 20971520 bytes, 40960 sectors
@@ -10,7 +10,7 @@
 Disk identifier: <removed>
 
 Device     Boot Start   End Sectors Id Type  Start-C/H/S End-C/H/S Attrs
-<removed>1       2048  8191    6144 83 Linux     7/107/1   31/34/2 
-<removed>2       8192 12287    4096 83 Linux     117/1/1  175/18/2 
+<removed>1       2048  8191    6144 83 Linux     0/32/33   0/130/2 
+<removed>2       8192 12287    4096 83 Linux     0/130/3   0/195/3 
 -------------------
 
}}}-diff

 FAILED (fdisk/mbr-nondos-mode-2nd-primary)
                : extended                    ...
diff-{{{
--- /home/runner/work/util-linux/util-linux/tests/expected/fdisk/mbr-nondos-mode-extended	2021-07-15 19:51:04.533586217 +0000
+++ /home/runner/work/util-linux/util-linux/tests/output/fdisk/mbr-nondos-mode-extended	2021-07-15 19:55:14.131688727 +0000
@@ -1,5 +1,5 @@
 Create extended partition
-9528631b198e44564f67f8ca97fa51b8 mbr-nondos-mode.img
+eed98bd91ea08e63ab6cd9aa18ce544e mbr-nondos-mode.img
 
 ---layout----------
 Disk <removed>: 20 MiB, 20971520 bytes, 40960 sectors
@@ -10,8 +10,8 @@
 Disk identifier: <removed>
 
 Device     Boot Start   End Sectors Id Type     Start-C/H/S End-C/H/S Attrs
-<removed>1       2048  8191    6144 83 Linux        7/107/1   31/34/2 
-<removed>2       8192 12287    4096 83 Linux        117/1/1  175/18/2 
+<removed>1       2048  8191    6144 83 Linux        0/32/33   0/130/2 
+<removed>2       8192 12287    4096 83 Linux        0/130/3   0/195/3 
 <removed>3      12288 40959   28672  5 Extended     0/195/4  2/140/10 
 -------------------
 
}}}-diff

 FAILED (fdisk/mbr-nondos-mode-extended)
                : logical                     ...
diff-{{{
--- /home/runner/work/util-linux/util-linux/tests/expected/fdisk/mbr-nondos-mode-logical	2021-07-15 19:51:04.533586217 +0000
+++ /home/runner/work/util-linux/util-linux/tests/output/fdisk/mbr-nondos-mode-logical	2021-07-15 19:55:14.251688727 +0000
@@ -1,5 +1,5 @@
 Create logical partitions
-db4406e7bc0773f234fd1db1b58b5997 mbr-nondos-mode.img
+7fda11a0988bcb4822105c70cf75c1f2 mbr-nondos-mode.img
 
 ---layout----------
 Disk <removed>: 20 MiB, 20971520 bytes, 40960 sectors
@@ -10,8 +10,8 @@
 Disk identifier: <removed>
 
 Device     Boot Start   End Sectors Id Type     Start-C/H/S End-C/H/S Attrs
-<removed>1       2048  8191    6144 83 Linux        7/107/1   31/34/2 
-<removed>2       8192 12287    4096 83 Linux        117/1/1  175/18/2 
+<removed>1       2048  8191    6144 83 Linux        0/32/33   0/130/2 
+<removed>2       8192 12287    4096 83 Linux        0/130/3   0/195/3 
 <removed>3      12288 40959   28672  5 Extended     0/195/4  2/140/10 
 <removed>5      14336 18431    4096 83 Linux       0/227/36   1/37/36 
 <removed>6      20480 24575    4096 83 Linux         1/70/6   1/135/6 
}}}-diff

 FAILED (fdisk/mbr-nondos-mode-logical)
                : logical-delete              ...
diff-{{{
--- /home/runner/work/util-linux/util-linux/tests/expected/fdisk/mbr-nondos-mode-logical-delete	2021-07-15 19:51:04.533586217 +0000
+++ /home/runner/work/util-linux/util-linux/tests/output/fdisk/mbr-nondos-mode-logical-delete	2021-07-15 19:55:14.371688727 +0000
@@ -1,5 +1,5 @@
 Delete logical partitions
-de85b8d74f52f307b9467ea4c33438cb mbr-nondos-mode.img
+e2b25d19e00bfe88ed44ca4ac9216c39 mbr-nondos-mode.img
 
 ---layout----------
 Disk <removed>: 20 MiB, 20971520 bytes, 40960 sectors
@@ -10,8 +10,8 @@
 Disk identifier: <removed>
 
 Device     Boot Start   End Sectors Id Type     Start-C/H/S End-C/H/S Attrs
-<removed>1       2048  8191    6144 83 Linux        7/107/1   31/34/2 
-<removed>2       8192 12287    4096 83 Linux        117/1/1  175/18/2 
+<removed>1       2048  8191    6144 83 Linux        0/32/33   0/130/2 
+<removed>2       8192 12287    4096 83 Linux        0/130/3   0/195/3 
 <removed>3      12288 40959   28672  5 Extended     0/195/4  2/140/10 
 <removed>5      26624 30719    4096 83 Linux       1/167/39  1/232/39 
 -------------------
}}}-diff

 FAILED (fdisk/mbr-nondos-mode-logical-delete)
                : logical-recreate            ...
diff-{{{
--- /home/runner/work/util-linux/util-linux/tests/expected/fdisk/mbr-nondos-mode-logical-recreate	2021-07-15 19:51:04.533586217 +0000
+++ /home/runner/work/util-linux/util-linux/tests/output/fdisk/mbr-nondos-mode-logical-recreate	2021-07-15 19:55:14.491688727 +0000
@@ -1,5 +1,5 @@
 Create another logical partition
-28d0cbe795535ee025dc7a4781516965 mbr-nondos-mode.img
+640065c08c007d78166954475cd08ff8 mbr-nondos-mode.img
 
 ---layout----------
 Disk <removed>: 20 MiB, 20971520 bytes, 40960 sectors
@@ -10,8 +10,8 @@
 Disk identifier: <removed>
 
 Device     Boot Start   End Sectors Id Type     Start-C/H/S End-C/H/S Attrs
-<removed>1       2048  8191    6144 83 Linux        7/107/1   31/34/2 
-<removed>2       8192 12287    4096 83 Linux        117/1/1  175/18/2 
+<removed>1       2048  8191    6144 83 Linux        0/32/33   0/130/2 
+<removed>2       8192 12287    4096 83 Linux        0/130/3   0/195/3 
 <removed>3      12288 40959   28672  5 Extended     0/195/4  2/140/10 
 <removed>5      26624 30719    4096 83 Linux       1/167/39  1/232/39 
 <removed>6      14336 18431    4096 83 Linux       0/227/36   1/37/36 
}}}-diff

 FAILED (fdisk/mbr-nondos-mode-logical-recreate)
                : 1st-primary-delete          ...
diff-{{{
--- /home/runner/work/util-linux/util-linux/tests/expected/fdisk/mbr-nondos-mode-1st-primary-delete	2021-07-15 19:51:04.533586217 +0000
+++ /home/runner/work/util-linux/util-linux/tests/output/fdisk/mbr-nondos-mode-1st-primary-delete	2021-07-15 19:55:14.607688727 +0000
@@ -1,5 +1,5 @@
 Delete primary partition
-6f1b62718cf8d83602d51de8944cee51 mbr-nondos-mode.img
+0b3611fc71ef2d02842feb621077767e mbr-nondos-mode.img
 
 ---layout----------
 Disk <removed>: 20 MiB, 20971520 bytes, 40960 sectors
@@ -10,7 +10,7 @@
 Disk identifier: <removed>
 
 Device     Boot Start   End Sectors Id Type     Start-C/H/S End-C/H/S Attrs
-<removed>2       8192 12287    4096 83 Linux        117/1/1  175/18/2 
+<removed>2       8192 12287    4096 83 Linux        0/130/3   0/195/3 
 <removed>3      12288 40959   28672  5 Extended     0/195/4  2/140/10 
 <removed>5      26624 30719    4096 83 Linux       1/167/39  1/232/39 
 <removed>6      14336 18431    4096 83 Linux       0/227/36   1/37/36 
}}}-diff

 FAILED (fdisk/mbr-nondos-mode-1st-primary-delete)
                : 1nd-primary-delete          ... OK
                : extended-delete             ... OK
                : first-sector-at-end         ...
diff-{{{
--- /home/runner/work/util-linux/util-linux/tests/expected/fdisk/mbr-nondos-mode-first-sector-at-end	2021-07-15 19:51:04.533586217 +0000
+++ /home/runner/work/util-linux/util-linux/tests/output/fdisk/mbr-nondos-mode-first-sector-at-end	2021-07-15 19:55:14.971688727 +0000
@@ -40,7 +40,7 @@
 
 Device     Boot Start   End Sectors Id Type  Start-C/H/S End-C/H/S Attrs
 <removed>1      20000 40959   20960 83 Linux     1/62/30  2/140/10 
-<removed>2       2048 19999   17952 83 Linux      1/63/9  14/25/10 
+<removed>2       2048 19999   17952 83 Linux     0/32/33   1/62/29 
 
 Partition table entries are not in disk order.
 -------------------
}}}-diff
```

**Comment by pali** [comment]
Tests stars failing after applying the last commit in this pull request ("libfdisk: (dos) Fix determining number of heads and sectors per track from MBR").

I'm looking at the output and it seems that currently (without the last patch) util-linux tests put into C/H/S part of MBR partitions just random numbers... Which can be explained in the commit message of the last patch (number of disk heads != head bits in the C/H/S-end value of the last partition). After applying the last patch it looks like that C/H/S values in partitions seems to be _more accurate_ (e.g. next partition use C/H/S + 1 value from previous partition).

**Comment by karelzak** [comment]
Yes, this is my conclusion too. 

Please, can you update the output of the tests too, so I can merge it without additional changes? Thanks!

**Comment by pali** [comment]
Ok! I updated test data in new commit. Seems that new CHS values introduced in new commit are more _sane_ as previous. E.g. first partition has lower CHS values than second / third partition.

If I looked correctly at diff, the only change in detailed fdisk output is changed CHS values, not LBA or other flags.

**Comment by pali** [comment]
Anyway, algorithm introduced in commit _libfdisk: (dos) Fix determining number of heads and sectors per track from MBR_ can be extended also for logical MBR partitions. So it could improve situation when all CHS/LBA values of primary partitions are linearly dependent (as linearity disallow to calculate _number of heads_ and _sectors per track_).

**Comment by pali** [comment]
I would suggest to extend manual page for fdisk and mention that C/H/S values filled by fdisk prior version in which would be this last commit from this PR are mostly random and would not work on systems which expect / require _correct_ C/H/S values. There is section _DOS mode and DOS 6.x WARNING_ in fdisk manpage which is probably suitable place. It could help people who need to do this FAT cylinder aligning as fdisk with `-c=dos -u=cylinders` (and probably also with `-H` and `-S`) is currently the only linux option how to (easily) achieve it.

**Comment by karelzak** [comment]
Can you send a patch with the desired change for the man page(s)? ;-)

**Pull request merged**
