### PR TITLE
travis: integrate util-linux with Coverity Scan

### PR DESCRIPTION
**Pull request by evverx**
For this to work, a daily cron job running on the master branch should be added: https://docs.travis-ci.com/user/cron-jobs/

The report can be found at https://scan.coverity.com/projects/karelzak-util-linux

### CODE REVIEW

**Comment by karelzak** [comment]
We use Coverity in Red Hat, but it will be definitely better to do it more early in the upstream tree. Thanks!

**Comment by karelzak** [comment]
The cron job added. Thanks.

**Comment by evverx** [comment]
@karelzak I'm not sure why it hasn't been triggered yet. Usually cron jobs are scheduled almost as soon as they are added. Could it be that the "don't run if there has been a build in the last 24 hours" option was chosen instead of the "always run" option?

**Comment by karelzak** [comment]
Changed to "Always run", we will see.

**Comment by evverx** [comment]
Looks like it was run successfully in https://travis-ci.org/github/karelzak/util-linux/builds/708276298 about three hours ago so it seems to be working. I haven't received a notification from Coverity Scan though but I guess I just need to tweak my email settings there.

**Pull request merged**
