### PR TITLE
Introduce uuid_unparse_f() and allow unparsing without dashes.

### PR DESCRIPTION
**Pull request by vs49688**
Not entirely sure if this belongs in `libuuid`, but here it is anyway.

### CODE REVIEW

**Comment by vs49688** [comment]
CI failure is a `hwclock` issue, nothing to do with this:
```
hwclock: system to hw                   ... FAILED (offsets 72.87.88.202: +0.016996 -0.995491 +/-1.012487)
```

**Comment by karelzak** [comment]
Do you have any use-case where non-dash UUIDs are necessary/used? (just out of curiosity)

I'm not sure about the function name, cannot we come up with something more descriptive? What about uuid_unparse_formatted()?

**Comment by vs49688** [comment]
My specific use case is to use them as access keys (which can only contain `[a-zA-Z0-9]`).

`uuid_unparse_formatted()` works, I was just trying to keep it short.

On a side-note, I just checked https://tools.ietf.org/html/rfc4122#section-3 and it appears that non-dashed UUIDs actually violate the spec, so perhaps this is better as application-specific code...

**Comment by karelzak** [comment]
libuuid uuid_t is opaque type, so the application should not expect anything and should not use it for example as an array to convert it to something else. It means use libuuid and unparse by application code will be pretty dirty... 

It seems the best is to use for example uuid_unparse_lower() and remove '-' from the string in your code by some trivial function like https://github.com/karelzak/util-linux/blob/master/include/strutils.h#L312

Seems like the problem is solved ;-)

**Pull request closed without merging**
