### PR TITLE
Fix some compiler warnings

### PR DESCRIPTION
**Pull request by rudimeier**
Some of these fixes may be too ugly ... you will see.

FYI I've enabled OSX travis build on my private ul clone. It builds already with some additional hacks:
https://travis-ci.org/rudimeier/util-linux/builds/108523108

### CODE REVIEW

**Comment by rudimeier** [comment]
One additional thought about printf forrmat strings for timeval.tv_usec.

We have still a few places left where we cast tv_usec and even tv_sec to int. I was not sure if we should also use "%ld" and long there.
see ```git grep "(int).*tv_.*sec"```

**Comment by karelzak** [comment]
It's long, so use 
```
%ld", (long) tv.tv_usec
```
seems like a valid way (although I hate "long" due to 32/64-bit variability).

**Comment by rudimeier** [comment]
Karel Zak wrote:
> The question is if we still need these extra fallbacks for at* functions. It would be nice
> to remove it and use everywhere what provides libc...
> (yes, irrelevant issue for this patch, just brainstorming:-)

The new  libsmartcols/samples/tree.c  is using fstatat already without build condition. This fails on OSX <=10.9 (2013). Anyway I will remove all fallbacks and use HAVE_OPENAT build conditions. Non-Linux systems will not miss many programs because we are using these at function mostly in Linux-only build conditions.

**Comment by karelzak** [comment]
On Fri, Feb 19, 2016 at 05:53:39AM -0800, Ruediger Meier wrote:
> Karel Zak wrote:
> > The question is if we still need these extra fallbacks for at* functions. It would be nice
> > to remove it and use everywhere what provides libc...
> > (yes, irrelevant issue for this patch, just brainstorming:-)
> 
> The new  libsmartcols/samples/tree.c  is using fstatat already

ah..  this is completely unimportant stuff, no problem to disable on
non linux ;)

> without build condition. This fails on OSX <=10.9 (2013). Anyway I
> will remove all fallbacks and use HAVE_OPENAT build conditions.
> Non-Linux systems will not miss many programs because we are using
> these at function mostly in Linux-only build conditions.

OK. Thanks, but don't add "if HAVE_OPENAT" to the Makefiles, I'd like
to keep only BUILD_* conditions there, all these dependencies should be
resolved in ./configure, for example:

  UL_REQUIRES_HAVE([switch_root], [openat], [openat function])

 Karel

-- 
 Karel Zak  <kzak@redhat.com>
 http://karelzak.blogspot.com

**Pull request merged**
