### PR TITLE
discard null_blk_device

### PR DESCRIPTION
**Pull request by DongDongJu**
null_blk is new module for simulating multi queue device. ( https://www.kernel.org/doc/Documentation/block/null_blk.txt ) So It can't make any file system feature on that. but mkfs passed this thing.

### CODE REVIEW

**Comment by karelzak** [comment]
I'm not sure about this patch. 

The goal is to minimize number of places where we in user-space do any policy for kernel stuff. What happen if you call mkfs for the device? I guess you will see error message or so, right?

And note that "mkfs" is deprecated in favour of filesystem specific mkfs.<type> utils.

**Comment by ehem** [comment]
I also notice this patch uses spaces instead of tabs.

**Comment by DongDongJu** [comment]
@karelzak It's mother of other some mkfs.*  daemons. and it does not show any message for null-blk devices. @ehem thks

**Comment by karelzak** [comment]
NACK, Sorry -- we do not want hardcode device names to the utils. closing.

**Pull request closed without merging**
