### PR TITLE
Fix minor typos

### PR DESCRIPTION
**Pull request by yurchor**
Many thanks in advance for reviewing.

### CODE REVIEW

**Comment by evverx** [comment]
Speaking of typos, @jschleus I wonder if it would be possible to generate codespell reports for this repository by analogy with https://fossies.org/linux/test/systemd-master.tar.gz/codespell.html.

**Comment by jschleus** [comment]
No problem, here the according URL:

&nbsp;&nbsp;https://fossies.org/linux/test/util-linux-master.tar.gz/codespell.html

I classified the name `seperator` in fdisk-list.[ch] as "false positive" (although formally a misspelling).  Let me know if some other words or files are better to be ignored by the spelling check..

Just for information there are also three supplemental pages: https://fossies.org/linux/test/util-linux-master.tar.gz/codespell_conf.html showing some used "codespell" configurations, https://fossies.org/linux/test/util-linux-master.tar.gz/codespell_fps.html showing all resulting obvious "false positives" and https://fossies.org/linux/test/util-linux-master.tar.gz/codespell_hist.html showing changes regarding found spelling errors compared to previous analyzed versions.

**Comment by evverx** [comment]
@jschleus thank you!

Interestingly, looking at the report it seems even though codespell found a lot of typos it couldn't find any of the typos fixed in this PR.

**Comment by yurchor** [comment]
> @jschleus thank you!
> 
> Interestingly, looking at the report it seems even though codespell found a lot of typos it couldn't find any of the typos fixed in this PR.

Actually, the "successfull" is found which is (with "unsupported") was a trigger for this PR.

**Comment by jschleus** [comment]
Oops, this is somewhat disappointing. The used basic tool "codespell" is at least principally "pretty primitive" and 
checked only for the exact misspelled words (currently 29021 ones). Although nearly all corrected words of the PR are found in the "codespell" own dictionary file the according misspelled variants are currently still missing. At least I have put them now into Fossies small own extra dictionary file and forced a rerun (but that is naturally not a general solution). By the way, incorrectly doubled words are principally not detected.

**Pull request merged**
