### PR TITLE
Update de.po

### PR DESCRIPTION
**Pull request by toddy**
Fix translation issues

### CODE REVIEW

**Comment by karelzak** [comment]
We use translatioproject.org to maintain translations. It's better to inform DE maintainers than directly update po/ stuff in the package. @mariobl ?

**Comment by mariobl** [comment]
OK, I will das These fixes to the next .po file I upload to the TP robot; no need to write an extra mail to the German TP team.

But remember: If a project developer decides to maintain translations at the GNU TP, then it is not allowed to accept .po files from other sources. And it wouldn't make sense at all: After the next sync from TP, any upstream changes would get overwritten because there's no way to get such fixes into the .po files there; unless you contact the translators directly.

**Comment by mariobl** [comment]
> OK, I will das These fixes to the next .po file I upload to the TP robot; no need to write an extra mail to the German TP team.

F***ing autocorrection... I meant I will include your fixes in the next .po file.

**Comment by mariobl** [comment]
I've just sent an updated de.po to the TP robot. Thanks for the corrections.

**Comment by karelzak** [comment]
Thanks, guys. Closing.

**Pull request closed without merging**
