### PR TITLE
Add support for signed verity devices

### PR DESCRIPTION
**Pull request by bluca**
https://gitlab.com/cryptsetup/cryptsetup/merge_requests/69 was merged in cryptsetup, so we can use the new crypt_activate_by_signed_key if available to make use of the kernel's CONFIG_DM_VERITY_VERIFY_ROOTHASH_SIG feature.

Also fix a corner case where rc was being overwritten when parsing options.

### CODE REVIEW

**Comment by karelzak** [comment]
Thanks. I merged the "rc" bugfix now, the rest will be merged after v2.35 release.

**Comment by bluca** [comment]
Thanks!

**Comment by bluca** [comment]
Last push added a check to ensure that when reusing an open device either both were signed or none were, using the new flag added by https://gitlab.com/cryptsetup/cryptsetup/commit/1be631f43fce7bfb60486106c9cbdd45acfb1cd4

**Comment by karelzak** [comment]
Merged. Thanks!

**Comment by bluca** [comment]
thanks!

**Pull request merged**
