### PR TITLE
tests: take exit codes into account

### PR DESCRIPTION
**Pull request by evverx**
In its current form the testsuite isn't suitable for running
fuzz targets because it ignores exit codes and relies solely
on diffs (that unfortunately aren't helpful because the nondeterministic
nature of fuzz targets makes it kind of hard to specify expected output
in advance). This patch is supposed to address the "exit code" issue for now.

### CODE REVIEW

**Comment by evverx** [comment]
Note that it's half broken because of https://github.com/karelzak/util-linux/issues/1072 but assuming fuzz targets will always be run with `ts_run` it should be fine.

**Comment by evverx** [comment]
It seems the tests like `mbr-err-primary` that can legitimately return non-zero exit codes are failing now. Looks like another option would be to keep ignoring exit codes there if tests have nothing to do with fuzzing.

**Comment by karelzak** [comment]
Yes, ts_run (or so) should be mandatory for memory-leaks detection and fuzzers.

It would be nice to support extra variable (TS_IGNORE_EXITCODE="yes") to the beginning of the test where we do not care about exit code. Can you update your patch to support it and use it in `mbr-err-primary`?

Some time ago I have thought about options for ts_run, something like "ts_run noexitcode nofuzz -- command". Not sure how difficult is it to implement.

**Comment by evverx** [comment]
>  Can you update your patch to support it and use it in mbr-err-primary?

Will do.

> Some time ago I have thought about options for ts_run, something like ts_run noexitcode nofuzz -- command. Not sure how difficult is it to implement.

I don't think it's hard to get `ts_run` to support options but `noexitcode` (or any other option) would have to be passed to `ts_finalize` (where exit codes and diffs are analyzed) as well. It seems at this point global variables are better in terms of passing data between functions.

**Comment by evverx** [comment]
I moved it to https://github.com/karelzak/util-linux/pull/1068

**Pull request closed without merging**
