### PR TITLE
travis: switch to Bionic

### PR DESCRIPTION
**Pull request by evverx**
To judge from fc412fe4cee960, back in 2016 it was the latest version
of Ubuntu available on Travis CI. Now build tools there are too old
for testing purposes.

Other than that, Ubuntu Trusty hasn't been supported at https://apt.llvm.org/
since August 2019, which makes it kind of hard at this point to bring the latest clang
along with ASan, UBsan, Msan and libFuzzer to Travis CI.

### CODE REVIEW

**Comment by evverx** [comment]
Blocked by https://github.com/karelzak/util-linux/issues/1076 and https://github.com/karelzak/util-linux/issues/1077

**Comment by evverx** [comment]
It seems to be working now. Tomorrow hopefully I'll replace the hard-coded values to make it easier to switch to the next version of clang/gcc once they're available.

**Comment by karelzak** [comment]
OK, I'll wait for the update.

**Comment by evverx** [comment]
To judge from https://travis-ci.org/github/karelzak/util-linux/builds/703664282 where I switched from gcc-10/clang-10 to gcc-9/clang-9 by changing just the compiler option in `.travis.yml`
```diff
diff --git a/.travis.yml b/.travis.yml
index ec1284717..12a247d91 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -7,8 +7,8 @@ git:
   depth: 1500

 compiler:
-  - gcc-10
-  - clang-10
+  - gcc-9
+  - clang-9

 env:
   - MAKE_CHECK="nonroot"
```
I think it's safe to say that that part is more or less maintainable and the PR should be good to go. @karelzak could you take a look?

**Comment by evverx** [comment]
By the way, trying to make sure I didn't break anything I looked for places where `travis_install` is used and came across the following paragraph
https://github.com/karelzak/util-linux/blob/f9a4f93584fe6e0a8eef413c0a72b2ef7f075789/Documentation/howto-tests.txt#L129-L146

Is drone.io still used? If not, I can delete that in a follow-up PR so as not to confuse contributors.

**Comment by karelzak** [comment]
Merged, thanks! I have updated the Documentation/howto-tests.txt, drone.io seems dead thing -- I have added LGTM.com.

**Comment by karelzak** [comment]
Ah, yesterday I get an email to re-activate drone.io ;-) It seems it works, but all the previous settings probably lost. I'll ignore it for now.

**Pull request merged**
