### PR TITLE
libsmartcols: python bindings via swig

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Reference: https://github.com/karelzak/util-linux/issues/134
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
This is simpliest way to autogenerate python bindings. Actually swig could generate C++, ruby, tcl, perl bindings, but I did only python.

I'm still unsure how to switch python versions 2 vs 3, but I hope you can do this.

**Comment by ignatenkobrain** [comment]
@karelzak `libtool: install: error: relink `_libsmartcols.la' with the above command before installing it`, have no idea how to fix it in travis.

**Comment by karelzak** [comment]
Thanks, I'll play with it next week.

**Comment by karelzak** [comment]
Thanks you invest your time to this task, but frankly the result from Python point of view seems poor. It would be nice to have something like:

tb = Table()
tb.add_colum("NAME", 0.1, SCOLS_FL_TREE)

ln = tb.add_line()
ln.set_data(COL_NAME, "Father Adam")

**Comment by ignatenkobrain** [comment]
I totally agree, but for this I think we need to write some wrappers like `class scols.Table {}` in C++ manner. Unfortunately I don't have time for this, sorry =(

But would be great to get python bindings, because we want to use libsmartcols in DNF (https://dnf.baseurl.org/)

**Comment by karelzak** [comment]
OK, I'll try to invest some time to this task.

**Comment by ignatenkobrain** [comment]
@karelzak Please take a look at repo: https://github.com/ignatenkobrain/pylibsmartcols

Is that idea OK for you? If yes - I will handle more function and will write tests and docs and then will explode it here.

**Comment by karelzak** [comment]
Seems really better!  Is it necessary to use cmake? :-)

**Comment by ignatenkobrain** [comment]
No, I will finins bindings with cmake and then will incorporate it here
with automake

On Mon, Dec 7, 2015, 1:15 PM Karel Zak <notifications@github.com> wrote:

> Seems really better! Is it necessary to use cmake? :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/karelzak/util-linux/pull/229#issuecomment-162508730>.
>
-- 

-Igor Gnatenko

**Comment by ignatenkobrain** [comment]
#246

**Pull request closed without merging**
