### PR TITLE
Support /usr/lib/os-release, in addition to /etc/os-release.

### PR DESCRIPTION
**Pull request by xnox**
Signed-off-by: Dimitri John Ledkov <dimitri.j.ledkov@intel.com>

### CODE REVIEW

**Comment by karelzak** [comment]
Thanks for your patch, I see two issues:

1/
http://www.freedesktop.org/software/systemd/man/os-release.html

The file /etc/os-release takes precedence over /usr/lib/os-release. Applications should check for the former, and exclusively use its data if it exists, and only fall back to /usr/lib/os-release if it is missing.

...it would be nice modify the patch to follow os-release man page.

2/ 
I really don't like the extra "trying legacy" warning in the patch. We usually don't use such warnings in code.

**Comment by xnox** [comment]
ok - I'll switch it around.
ok - s/legacy/sysconf/, or admin, or site ?
ok - will only have one warning if failed to load any.

**Comment by karelzak** [comment]
I think it's enough to print only one warning if there is no any os-reelase file at all, so try /etc/os-release, if cannot open, then try /usr/lib/os-release, if cannot open, then print warning.

**Comment by karelzak** [comment]
Fixed by commit b28842ae67557f503ae097d5101cbe0a93fda39d.

**Pull request closed without merging**
