### PR TITLE
libsmartcols: implement SCOLS_FL_WRAP

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Reference: https://github.com/karelzak/util-linux/issues/257
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
Known issue: with `SCOLS_FL_RIGHT` it does not wrapping

Known missing feature: it just breaks line instead of real word wrapping (could be done after release because will not break API)

**Comment by ignatenkobrain** [comment]
oh crap, also we will loose color here. I will fix it.

**Comment by karelzak** [comment]
Mix SCOLS_FL_RIGHT and SCOLS_FL_WRAP for the same column seems like nonsense. I don't think we need to support it.

**Comment by ignatenkobrain** [comment]
ok, fixed. Still have some warning in valgrind, but looks like everything works:
```
==24719== Conditional jump or move depends on uninitialised value(s)
==24719==    at 0x4E4899D: wc_truncate (mbsalign.c:239)
==24719==    by 0x4E48EE2: mbs_truncate (mbsalign.c:299)
==24719==    by 0x4E44BD1: print_data (table_print.c:366)
==24719==    by 0x4E44E2E: print_line (table_print.c:568)
==24719==    by 0x4E454AF: print_table (table_print.c:672)
==24719==    by 0x4E454AF: scols_print_table (table_print.c:1169)
==24719==    by 0x400AA0: main (in /home/brain/a.out)
==24719== 
```

**Pull request merged**
