### PR TITLE
Fix PID namespace persistence

### PR DESCRIPTION
**Pull request by michael-dev**
After unshare(...) is called, /proc/self/ns/pid does not change.
Instead, only /proc/self/ns/pid_for_children is affected. So bind-mounting /proc/self/ns/pid results in the original namespace getting bind-mounted.

Fix this by instead bind-mounting ns/pid_for_children.

### CODE REVIEW

**Comment by karelzak** [comment]
Please, send the patch to util-linux@vger.kernel.org mailing list. I'd like to see a review from Eric Biederman. Thanks.

**Comment by michael-dev** [comment]
Raised in https://github.com/karelzak/util-linux/issues/935 or https://github.com/karelzak/util-linux/issues/798#issuecomment-493950110

**Comment by michael-dev** [comment]
Raised in https://github.com/karelzak/util-linux/issues/935 or https://github.com/karelzak/util-linux/issues/798

**Comment by karelzak** [comment]
Committed as https://github.com/karelzak/util-linux/commit/0d5260b66c5581c8a5855a5f49e298e48e8baf82. Thanks.

**Pull request closed without merging**
