### PR TITLE
loopdev: use LOOP_CONFIGURE ioctl

### PR DESCRIPTION
**Pull request by franksinankaya**
Prefer to use the new LOOP_CONFIGURE ioctl.
https://lwn.net/Articles/820408/

Signed-off-by: Sinan Kaya <sinan.kaya@microsoft.com>

### CODE REVIEW

**Comment by franksinankaya** [comment]
seeing some regression on local tests. Will come back after more testing.

**Comment by franksinankaya** [comment]
apparently, it is a wrong alarm

**Comment by karelzak** [comment]
Unfortunately, I see a regression here. It seems LO_FLAGS_PARTSCAN does not work (I have 5.8.10-100.fc31.x86_64).
```
# dd if=/dev/zero of=img bs=1MiB count=10
# echo ',,L' | sfdisk img
```
Old version:
```
# losetup --partscan --find --show img 
/dev/loop0
# lsblk /dev/loop0
NAME      MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
loop0       7:0    0  10M  0 loop 
└─loop0p1 259:5    0   9M  0 part 
```
New version
```
# ./losetup --partscan --find --show img 
/dev/loop0
# lsblk /dev/loop0
NAME  MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
loop0   7:0    0  10M  0 loop 
```
Note that losetup calls the ioclt with the flags as expected, strace:
```
ioctl(4, LOOP_CONFIGURE, {fd=3, block_size=0, info={lo_offset=0, lo_number=0, lo_flags=LO_FLAGS_PARTSCAN, lo_file_name="/home/projects/util-linux/4K.img", ...}}) = 0
```

So, it seems like a kernel problem ...

**Comment by karelzak** [comment]
Ah... it works as expected after update to 5.9.0-0.rc7. Going to merge it. 

Thanks for your work!

**Pull request merged**
