### PR TITLE
add a fuzzer for mnt_table_parse_stream

### PR DESCRIPTION
**Pull request by evverx**
The fuzzer is supposed to cover `mnt_table_parse_stream`, which is
used by systemd to parse /proc/self/mountinfo. The systemd project
has run into memory leaks there at least twice:

https://github.com/systemd/systemd/pull/12252#issuecomment-482804040
https://github.com/systemd/systemd/issues/8504

so it seems to be a good idea to continuously fuzz that particular
function.

The patch can be tested locally by installing clang and running
./tools/oss-fuzz.sh. Currently the fuzzer is failing with
```
=================================================================
==96638==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 216 byte(s) in 1 object(s) allocated from:
    #0 0x50cd77 in calloc (/home/vagrant/util-linux/out/test_mount_fuzz+0x50cd77)
    #1 0x58716a in mnt_new_fs /home/vagrant/util-linux/libmount/src/fs.c:36:25
    #2 0x54f224 in __table_parse_stream /home/vagrant/util-linux/libmount/src/tab_parse.c:728:9
    #3 0x54eed8 in mnt_table_parse_stream /home/vagrant/util-linux/libmount/src/tab_parse.c:804:8
    #4 0x5448b2 in LLVMFuzzerTestOneInput /home/vagrant/util-linux/libmount/src/fuzz.c:19:16
    #5 0x44cc88 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/vagrant/util-linux/out/test_mount_fuzz+0x44cc88)
    #6 0x44d8b0 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) (/home/vagrant/util-linux/out/test_mount_fuzz+0x44d8b0)
    #7 0x44e270 in fuzzer::Fuzzer::MutateAndTestOne() (/home/vagrant/util-linux/out/test_mount_fuzz+0x44e270)
    #8 0x450617 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (/home/vagrant/util-linux/out/test_mount_fuzz+0x450617)
    #9 0x43adbb in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/vagrant/util-linux/out/test_mount_fuzz+0x43adbb)
    #10 0x42ad46 in main (/home/vagrant/util-linux/out/test_mount_fuzz+0x42ad46)
    #11 0x7fa084f621a2 in __libc_start_main (/lib64/libc.so.6+0x271a2)

SUMMARY: AddressSanitizer: 216 byte(s) leaked in 1 allocation(s).
INFO: to ignore leaks on libFuzzer side use -detect_leaks=0.
```

Once the bug is fixed and the OSS-Fuzz counterpart is merged it should be possible
to turn on CIFuzz to make sure the fuzz target can be built and run for some time
without crashing: https://google.github.io/oss-fuzz/getting-started/continuous-integration/

### CODE REVIEW

**Comment by karelzak** [comment]
I have fixed the leak. Thanks for report.

**Comment by karelzak** [comment]
The LibFuzzer integration looks like a cool idea. I'd like to use it for more stuff in the package (libfdisk, last(1), etc.) but we need to integrate in a better way ;-)

* add --with-clang to ./configure.ac to overwrite the default gcc (and to avoid user-unfriendly export CC=clang), we can use this feature also for static analyzer too
* add --enable-clang-fuzz (the --with-clang should be unnecessary in this case)
* define all the compiler options in ./configure script and exported it to the makefiles by FUZZER_LDFLAGS (CFLAGS, ...)
* add AC_DEFINE(HAVE_FUZZING_ENGINE) and  AM_CONDITIONAL(BUILD_FUZZING)
* add fuzz_PROGRAMS= to Makefile.am
* add "fuzz-programs" target to Makefile.am
* for extra test binaries we use #ifdef TEST_PROGRAM, maybe we can use #ifdef FUZZ_PROGRAM in .c files to avoid
extra files (it means use libmount/src/tab.c rather extra file libmount/src/fuzz) and to keap tests neer to the code
* we can also add fuzer to options strings parser (libmount/src/optstr.c)
* add --fuzz to tests/run.sh to execute fuzzer tests, otherwise ignore these tests
* use tests/fuzz/name/ to execute the tests
* in tests/functions.sh:ts_init_env() define TS_FIZZDIR="$top_builddir/tests/fuzz/$TS_COMPONENT" (and mkdir)
* cleanup tests/fuzz on "make clean"
* write individual fuzz tests like other util-linux tests (for example tests/ts/libmount/fuzz)
* add Documentation/howto-fuzz-tests
* the typical use-case:
```
./configure --enable-clang-fuzz
make fuzz-programs
./tests/run.sh --fuzz
```
* add CI stuff ( .github/workflows/main.yml, ...) to compile "fuzz-programs" and execute ./tests/run.sh --fuzz

Does it make sense? -- It seems like more work, but if we want to use it in CI, maintain it for a long time, and use it for more utils then it would be nice to create some infrastructure.

**Comment by evverx** [comment]
> I have fixed the leak. Thanks for report.

Thank you! Since OSS-Fuzz is fuzzing my fork at the moment I've just rebased the branch on top of that commit so that it can close https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=23722 and keep accumulating the corpus

> we need to integrate in a better way ;-)

Agreed. I'll get back to this PR on Monday. Though I think some points seem to be incompatible with https://google.github.io/oss-fuzz/getting-started/new-project-guide/#Requirements. I'll try to figure out how to combine them.

**Comment by karelzak** [comment]
Note that I'd like to call fuzz locally (in regression tests) with some very small time-limits to detect stupid bugs.

For integration with CI services, it will be probably necessary to call directly individual script/binaries. This is also possible with our regression tests, just call "./tests/ts/foo/bar".

**Comment by evverx** [comment]
> For integration with CI services, it will be probably necessary to call directly individual script/binaries without time limits (just call "./tests/ts/foo/bar", it's already supported by our test suite).

Unfortunately just running binaries isn't enough. Additionally CI services would have to maintain the corpora, ignore known issues, take coverage into account and so on. That's what [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) is basically for and I'd stick to it (given that `util-linux` has already been kind of integrated into OSS-Fuzz). I'm not sure if it helps but at https://github.com/systemd/systemd/actions?query=workflow%3ACIFuzz+is%3Afailure it should be possible to see it in action.

>  * use tests/fuzz/name/ to execute the tests
> * in tests/functions.sh:ts_init_env() define TS_FIZZDIR="$top_builddir/tests/fuzz/$TS_COMPONENT" (and mkdir)
> * cleanup tests/fuzz on "make clean"
> * write individual fuzz tests like other util-linux tests (for example tests/ts/libmount/fuzz).

Now that I more or less understand how the testsuite works I'm a little confused. Should the tests be kept in `tests/ts/*`? If so, what should be kept in "tests/fuzz"?

**Comment by karelzak** [comment]
The directories:
* tests/ts   --  test scripts
* tests/output  --  tests output (removable, not maintained in repo)
* tests/expected -- expected output, we generate diff between output/ and expected/
* tests/diff -- the diff ^^^
* tests/fuzz -- fuzzer work dir, a place for recorded inputs and leaks reports -- it would be possible to use output/ as work directory, but I'm not sure if mix it all together makes sense. Not sure, just suggestion :-)

**Comment by karelzak** [comment]
> Additionally CI services would have to maintain the corpora, ignore known issues, take coverage into account and so on. That's what CIFuzz is basically for and I'd stick to it (given that util-linux has already been kind of integrated into OSS-Fuzz). 

Where is it maintained -- is it expected in the project repo? 

Sorry, for stupid questions, but  I have zero experience with it -- what I want to is to make it possible check for stupid bugs (like the last in libmount parser) locally and keep it easy to use for CI with minimal maintenance overhead. If it will be possible to use our tests/ infrastructure than I'll be happy. Another solution is to use something completely separated (add fuzz/ dir etc.)

**Comment by evverx** [comment]
> Where is it maintained -- is it expected in the project repo?

Yes, it should be in the repository. Now that https://github.com/google/oss-fuzz/pull/4063 is merged, the last commit in https://github.com/karelzak/util-linux/pull/1088 (where `.github/workflows/cifuzz.yml` was added) should turn it on. FWIW the action wasn't triggered there because it's the first PR where it's appeared and since the PR came from my fork GitHub refused to run it. Once it's merged it should work in the sense that it will make sure the fuzzer can be built and run for 3 minutes without failing (which should help to catch issues like that memory leak in `libmount` when PRs are opened).

Since fuzz targets that are kept in the OSS-Fuzz repository are fragile and unmaintainable I'm still working on moving the fuzz target to the util-linux repository and integrating it into the testsuite.

**Comment by evverx** [comment]
@karelzak I think I'm slowly moving in the right direction :-)

In its current form the fuzz target is fully integrated into the testsuite and the build system so it can be built and run along with the other tests (after installing `clang`) locally with:
```
	$ ./tools/config-gen fuzz
	$ make check
```

I also tweaked the travis config and strategically placed a memory leak to make sure  `make check` can catch it and judging by https://travis-ci.org/github/karelzak/util-linux/jobs/712526004 where the fuzzer failed with:
```
diff-{{{
--- /dev/null	2020-07-28 11:31:59.540000134 +0000
+++ /home/travis/build/karelzak/util-linux/tests/output/fuzzers/test_mount_fuzz.err	2020-07-28 11:38:04.513407071 +0000
@@ -0,0 +1,34 @@
+INFO: Seed: 3746661145
+INFO: Loaded 1 modules   (23710 inline 8-bit counters): 23710 [0x969c00, 0x96f89e), 
+INFO: Loaded 1 PC tables (23710 PCs): 23710 [0x96f8a0,0x9cc280), 
+INFO:        0 files found in /home/travis/build/karelzak/util-linux/tests/output/fuzzers/test_mount_fuzz_workdir
+INFO:        1 files found in /home/travis/build/karelzak/util-linux/tests/ts/fuzzers/test_mount_fuzz_files
+INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
+INFO: seed corpus: files: 1 min: 4b max: 4b total: 4b rss: 29Mb
+
+=================================================================
+==9231==ERROR: LeakSanitizer: detected memory leaks
+
+Direct leak of 88 byte(s) in 1 object(s) allocated from:
+    #0 0x51ed02 in calloc (/home/travis/build/karelzak/util-linux/test_mount_fuzz+0x51ed02)
+    #1 0x551021 in mnt_new_table /home/travis/build/karelzak/util-linux/libmount/src/tab.c:86:7
+    #2 0x550c3b in LLVMFuzzerTestOneInput /home/travis/build/karelzak/util-linux/libmount/src/fuzz.c:14:14
+    #3 0x459031 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/travis/build/karelzak/util-linux/test_mount_fuzz+0x459031)
+    #4 0x458775 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) (/home/travis/build/karelzak/util-linux/test_mount_fuzz+0x458775)
+    #5 0x45b097 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (/home/travis/build/karelzak/util-linux/test_mount_fuzz+0x45b097)
+    #6 0x45b3f9 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (/home/travis/build/karelzak/util-linux/test_mount_fuzz+0x45b3f9)
+    #7 0x44a0ce in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/travis/build/karelzak/util-linux/test_mount_fuzz+0x44a0ce)
+    #8 0x472f12 in main (/home/travis/build/karelzak/util-linux/test_mount_fuzz+0x472f12)
+    #9 0x7f4c69d3db96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
+
+SUMMARY: AddressSanitizer: 88 byte(s) leaked in 1 allocation(s).
+
+INFO: a leak has been found in the initial corpus.
+
+INFO: to ignore leaks on libFuzzer side use -detect_leaks=0.
+
+MS: 0 ; base unit: 0000000000000000000000000000000000000000
+0x1,0x0,0x0,0x0,
+\x01\x00\x00\x00
+artifact_prefix='./'; Test unit written to ./leak-3c585604e87f855973731fea83e21fab9392d2fc
+Base64: AQAAAA==
}}}-diff
```
it seems to be working.

I'd appreciate it if you could take a look.

**Comment by evverx** [comment]
I've just added a fuzz target for `process_wtmp_file`. It was mostly inspired by #1097.

**Comment by karelzak** [comment]
Sorry for the delay. I had a vacation the last 2 weeks.

It works for me -- and it seems elegant now. So, thanks for all the work! I guess it's ready for merge, correct?

BTW, how is it expected to add another fuzzer test to libmount? It seems we need another libmount/src/fuzz.c file and test in tests/ts/fuzzers. Right?

Libmount supports multiple file-formats and it would be nice to add another stuff to the fuzzer,
for example add more  __mnt_new_table_from_file() calls with MNT_FMT_FSTAB, MNT_FMT_UTAB and MNT_FMT_SWAPS.

**Comment by karelzak** [comment]
Cool:
```
 $ ./tools/config-gen fuzz
 $ make  check-programs
 $ ./run.sh fuzzers
...
      fuzzers: test_last_fuzz                 ... OK
      fuzzers: test_mount_fuzz                ... OK

---------------------------------------------------------------------
  All 2 tests PASSED
---------------------------------------------------------------------
```
works locally as expected ;-)

**Comment by evverx** [comment]
> I guess it's ready for merge, correct?

Yes, I think it should be good to go.

> BTW, how is it expected to add another fuzzer test to libmount? It seems we need another libmount/src/fuzz.c file and test in tests/ts/fuzzers. Right?

That's correct. By analogy with `fuzz.c` a new file called, say, `fuzz_something.c` should be added to `libmount/src/` and `test_fuzz_something` should be added to `tests/ts/fuzzers` (probably along with testcases kept in `test_fuzz_something_files`).

> Libmount supports multiple file-formats and it would be nice to add another stuff to the fuzzer,
for example add more __mnt_new_table_from_file() calls with MNT_FMT_FSTAB, MNT_FMT_UTAB and MNT_FMT_SWAPS

I'll take a look.

I was planning to wait for the coverage report (https://oss-fuzz.com/coverage-report/job/libfuzzer_asan_util-linux/latest) to somewhat stabilize to figure out what else should be covered.

**Pull request merged**
