### PR TITLE
rename: fix/reverse the semantics of --no-overwrite in --symlink mode

### PR DESCRIPTION
**Pull request by g-raud**
The previous behaviour was to overwrite a symlink only when the new
destination did not exist, i.e. to avoid creating a symlink to an
existing file!  It had not been documented and it seems
counter-intuitive to me.  So the new behavior protects symlinks pointing
to existing targets from being changed.

### CODE REVIEW

**Comment by g-raud** [comment]
This pull request is based on PR #606.

**Comment by karelzak** [comment]
Good point. 

It would be nice to have this bugfix as independent patch against the current master. I'll merge it and then we can continue with --interactive patches. The independent patch could be also backported to the stable branches. Please ;-)

**Comment by g-raud** [comment]
On Tue, Mar 27, 2018 at 03:52:32AM -0700, Karel Zak wrote:
> Good point.
> 
> It would be nice to have this bugfix as independent patch against the current
> master. I'll merge it and then we can continue with --interactive patches. The
> independent patch could be also backported to the stable branches. Please ;-)

I rebased the pull request.

How do you handle backports?  Merge of the pull branch (containing only
the relevant commits of course)?  Merge of the merge of the pull branch?
Cherry pick of each commit independently?  Cherry pick of the merge?

Is the stable branch stable/v2.31 even though there is a tag v2.32?

**Comment by karelzak** [comment]
On Tue, Mar 27, 2018 at 01:20:01PM +0000, G.raud wrote:
> On Tue, Mar 27, 2018 at 03:52:32AM -0700, Karel Zak wrote:
> > Good point.
> > 
> > It would be nice to have this bugfix as independent patch against the current
> > master. I'll merge it and then we can continue with --interactive patches. The
> > independent patch could be also backported to the stable branches. Please ;-)
> 
> I rebased the pull request.
> 
> How do you handle backports?  Merge of the pull branch (containing only
> the relevant commits of course)?  Merge of the merge of the pull branch?
> Cherry pick of each commit independently?  Cherry pick of the merge?

Cherry-pick relevant patches from master

> Is the stable branch stable/v2.31 even though there is a tag v2.32?

I usually create stable branch when necessary -- usually before stable
release, because people almost always contribute to master only. 

It would be nice to have contributors to the stable branches too (for
example downstream maintainers), but it's probably too boring...

The stable/v2.32 has not been created yet (well, v2.32 is 6days old:-)

**Comment by g-raud** [comment]
On Tue, Mar 27, 2018 at 01:54:14PM +0000, Karel Zak wrote:
> On Tue, Mar 27, 2018 at 01:20:01PM +0000, G.raud wrote:
> > How do you handle backports? Merge of the pull branch (containing only
> > the relevant commits of course)? Merge of the merge of the pull branch?
> > Cherry pick of each commit independently? Cherry pick of the merge?
> 
> Cherry-pick relevant patches from master
> 
> > Is the stable branch stable/v2.31 even though there is a tag v2.32?
> 
> I usually create stable branch when necessary -- usually before stable
> release, because people almost always contribute to master only.
> 
> It would be nice to have contributors to the stable branches too (for
> example downstream maintainers), but it's probably too boring...
> 
> The stable/v2.32 has not been created yet (well, v2.32 is 6days old:-)

You need to create it so that I can create a pull request then; hashes
or tags are not valid PR bases.

**Comment by karelzak** [comment]
On Tue, Mar 27, 2018 at 10:29:15AM -0700, G.raud wrote:
> On Tue, Mar 27, 2018 at 01:54:14PM +0000, Karel Zak wrote:
> > The stable/v2.32 has not been created yet (well, v2.32 is 6days old:-)
> 
> You need to create it so that I can create a pull request then; hashes
> or tags are not valid PR bases.

Done, stable/v2.32 is there.

**Pull request merged**
