### PR TITLE
Add support for libeconf

### PR DESCRIPTION
**Pull request by thkukuk**
openSUSE plans to split the distribution provided configuration files from the changes the user makes. We will, similar to systemd, have a vendor directory below /usr with the distribution configuration files and applications will merge the configs at start. For this, we developed libeconf to make that easier.
This pull request implements libeconf support for util-linux and adds a configure option to specify the vendor directory below /usr. If none is specified, libeconf will read /etc/login.defs and merge possible overrides from /etc/login.defs.d. Else libeconf will read /usr/<vendor>/login.defs{.d} if /etc/login.defs does not exist and merge all overrides from /etc/login.defs.d.

### CODE REVIEW

**Comment by karelzak** [comment]
Hmm.. sounds like over-engineering, why do you want to merge anything? Sounds like pretty complicated semantic for end users...

Would be better to assume that user creates a copy and /etc provides complete local config file?

**Comment by karelzak** [comment]
... it would be better to move this discussion to our mailing list to see more opinions. Note that I don't see a problem to use /usr/{lib,etc}/login.defs is there is nothing in /etc, but the lib sounds strange.

**Comment by thkukuk** [comment]
> Hmm.. sounds like over-engineering, why do you want to merge anything? Sounds like pretty complicated semantic for end users...

No, it's not really complicated and what already done by some other applications like systemd.

Background:
https://github.com/thkukuk/atomic-updates_and_etc/blob/master/README.md
https://en.opensuse.org/openSUSE:Packaging_UsrEtc

> Would be better to assume that user creates a copy and /etc provides complete local config file?

That's a common solution by other distributions, but we don't like that at all as this does not solve any problem.

**Comment by thkukuk** [comment]
> ... it would be better to move this discussion to our mailing list to see more opinions. Note that I don't see a problem to use /usr/{lib,etc}/login.defs is there is nothing in /etc, but the lib sounds strange.

We want to unify it as far as possible, and having the logic in one lib makes it much simpler than re-implementing it again and again for every application (login.defs is read by at minimum 3 projects e.g.). Which also would mean, to fix a bug, you would need to touch 3 projects in this case. And it will be hard to keep all 3 projects in sync to read the configuration in the same way with the same result.

And: it's only optional, I explicit did not remove the old logindefs code, even if that would have made quite some things easier, as I'm pretty sure that not everybody want's to switch.

**Comment by thkukuk** [comment]
If you mean the long lists *.d directories: there is already an open issue to make this configureable to one directory (/etc/login.defs.d/*.defs), we don't plan to keep this long list.

**Comment by thkukuk** [comment]
@karelzak I have no experience with clang, thus I don't understand why that part of the check is failing. I'm not able to reproduce that myself, it's always passing. And all code changes made by me are #ifdef'd, so shouldn't be used/visible in that test run at all.

**Comment by karelzak** [comment]
@thkukuk it's OSX :-)

The code in the Makefile is strange, there should be probably test_logindefs_CFLAGS instead of test_logindefs_CPPFLAGS. I think you can ignore it for now. I'll play with it later.

**Comment by thkukuk** [comment]
What is the status here? The corresponding patches for shadow and Linux-PAM were already accepted upstream 2-3 month ago.

**Comment by karelzak** [comment]
Ah sorry, for the delay. I've been busy with something else. I'll merge it, but for the next release -- it's too late for the current v2.35 (sorry again...).

**Comment by thkukuk** [comment]
Any update on this one?

**Comment by karelzak** [comment]
Thorsten, can you send the patch to util-linux mailing list. I'd like to see more wide discussion about it. Maybe you can also add Lennart also to CC -- I guess (but not sure:-))  you have talked about it with him on All-Systems-Go in Berlin. Thanks!

**Comment by karelzak** [comment]
Merged. Thanks for your patience ;-) It will be in v2.36-rc1.

**Pull request merged**
