### PR TITLE
tests: fdisk: Layout with more details

### PR DESCRIPTION
**Pull request by pali**
Use fdisk -x instead of fdisk -l for printing layout in fdisk tests. This
can help debugging why some fdisk tests fail.

### CODE REVIEW

**Comment by karelzak** [comment]
Something is wrong here. Note, we use a regular file image here (not a loop or scsi_debug block device).
```
--- /home/projects/util-linux/util-linux/tests/expected/fdisk/mbr-nondos-mode-1st-primary-recreate      2021-07-14 13:49:54.6138
+++ /home/projects/util-linux/util-linux/tests/output/fdisk/mbr-nondos-mode-1st-primary-recreate        2021-07-14 13:50:05.4987
@@ -1,5 +1,5 @@
 Re-create 1st primary partition
-a5543ee1e3d2cf79913a56bae893a0f0 mbr-nondos-mode.img
+e21e16b7452d82e2a2810a1de8c3db05 mbr-nondos-mode.img
 
 ---layout----------
 Disk <removed>: 20 MiB, 20971520 bytes, 40960 sectors
@@ -10,6 +10,6 @@
 Disk identifier: <removed>
 
 Device     Boot Start   End Sectors Id Type  Start-C/H/S End-C/H/S Attrs
-<removed>1       2048  8191    6144 83 Linux     7/107/1   31/34/2 
+<removed>1       2048  8191    6144 83 Linux     0/32/33   0/130/2 
 -------------------
```
The checksum I have commented on in the https://github.com/karelzak/util-linux/pull/1385, but it seems that CHS is also unstable here...  (executed on x86_64).

**Comment by karelzak** [comment]
```
       fdisk: MBR - non-dos mode             ...
                : empty-pt                    ... OK
                : 1st-primary                 ... OK
                : 1st-active                  ... OK
                : 1st-primary-recreate        ... FAILED (fdisk/mbr-nondos-mode-1st-primary-recreate)
                : 2nd-primary                 ... FAILED (fdisk/mbr-nondos-mode-2nd-primary)
                : extended                    ... FAILED (fdisk/mbr-nondos-mode-extended)
                : logical                     ... FAILED (fdisk/mbr-nondos-mode-logical)
                : logical-delete              ... FAILED (fdisk/mbr-nondos-mode-logical-delete)
                : logical-recreate            ... FAILED (fdisk/mbr-nondos-mode-logical-recreate)
                : 1st-primary-delete          ... FAILED (fdisk/mbr-nondos-mode-1st-primary-delete)
                : 1nd-primary-delete          ... OK
                : extended-delete             ... OK
                : first-sector-at-end         ... FAILED (fdisk/mbr-nondos-mode-first-sector-at-end)
           ... FAILED (8 from 13 sub-tests)
```

The problem are two first partitons:
```--- /home/projects/util-linux/util-linux/tests/expected/fdisk/mbr-nondos-mode-logical   2021-07-14 13:49:54.613801054 +0200
+++ /home/projects/util-linux/util-linux/tests/output/fdisk/mbr-nondos-mode-logical     2021-07-14 13:50:05.667746385 +0200
@@ -1,5 +1,5 @@
 Create logical partitions
-db4406e7bc0773f234fd1db1b58b5997 mbr-nondos-mode.img
+7fda11a0988bcb4822105c70cf75c1f2 mbr-nondos-mode.img
 
 ---layout----------
 Disk <removed>: 20 MiB, 20971520 bytes, 40960 sectors
@@ -10,8 +10,8 @@
 Disk identifier: <removed>
 
 Device     Boot Start   End Sectors Id Type     Start-C/H/S End-C/H/S Attrs
-<removed>1       2048  8191    6144 83 Linux        7/107/1   31/34/2 
-<removed>2       8192 12287    4096 83 Linux        117/1/1  175/18/2 
+<removed>1       2048  8191    6144 83 Linux        0/32/33   0/130/2 
+<removed>2       8192 12287    4096 83 Linux        0/130/3   0/195/3 
<removed>3      12288 40959   28672  5 Extended     0/195/4  2/140/10
 <removed>5      14336 18431    4096 83 Linux       0/227/36   1/37/36
 <removed>6      20480 24575    4096 83 Linux         1/70/6   1/135/6



```

**Comment by pali** [comment]
Well, this pull request just extends test output. It is independent of #1385. It does not change any test, nor checksum. Test files are updated just to include extended output from `-x` argument.

Therefore these changes should not change any checksum and seems that CI tests did not triggered any issue.

**Comment by karelzak** [comment]
Ah, not sure why, but I've expected it follows #1385 ;-)

**Pull request merged**
