### PR TITLE
Import of Asciidoc man pages is finished

### PR DESCRIPTION
**Pull request by mariobl**
The *.adoc files are now in a shape to be published to the users.

Some notes:

As recommended, I've removed the *roff man pages. But for the links, I didn't know what to do, so they are still present.

After doing first tests with the i18n stuff, I encountered some peculiarities which prevent Po4a from both creating a proper template and a correct man page. You may expect formatting changes in the future.

The Autotools stack doesn't work yet. As described in the mailing list, I encountered a file permission problem. When this gets fixed, don't forget to add the extra variables from the uuid and misc-utils man pages to the asciidoctor command.

Regarding a better formatting of "mailto:" links, I wrote to the [Asciidoctor mailing list](https://discuss.asciidoctor.org/How-to-change-rendering-of-links-in-man-pages-tt8575.html), but haven't got an answer yet. Maybe it is impossible to customize the *roff output without creating a new Ruby module, but maybe it's a hint for the Asciidoctor developers to change the default "mailto:" rendering behavior in the future.

### CODE REVIEW

**Comment by mariobl** [comment]
Karel, please don't merge my commits for now. I just found some other things to fix, which needs a few more days. Some characters are not displayed at all, especially the "+", which needs to be escaped because it's also a control character. And moreover, the empty lines within paragraphs using `+{nbsp}+` (non-breakable spaces) are not a generic solution.

Well, Asciidoctor is better readable and writable than *roff, but sometimes it has its very own peculiarities. Unfortunately, after the import with Pandoc and comparing the result with [asciidoctor.1.adoc](https://raw.githubusercontent.com/asciidoctor/asciidoctor/master/man/asciidoctor.adoc) I thought all is OK and treated that man page as a reference, but it isn't.

If you need to fix anything in the current *roff man pages, no worries, I will track your changes and incorporate into the *.adoc files.

When the import is *really* finished, then I will rewrite _man-common/manpage-stub.adoc_ to summarize the formatting which usually will be needed in the future.

**Comment by karelzak** [comment]
I have created PR for you to fix the issue with the links and other issues https://github.com/mariobl/util-linux/pull/1

**Comment by mariobl** [comment]
> I have created PR for you to fix the issue with the links and other issues [mariobl#1](https://github.com/mariobl/util-linux/pull/1)

Many thanks, it works now without errors!

**Comment by mariobl** [comment]
I'm finished - however, I wrote this already more than once ;) I've reviewed all of the *.adoc files once again. Formatting and indentations are OK so far, although with some concessions regarding line breaks, see [my Po4a bug report](https://github.com/mquinson/po4a/issues/299).

Moreover, a Po4a config file is present, and we have an initial translation template (man-common/util-linux-man.pot, with 5341 gettext messages). The template file can be updated with `po4a po4a.cfg`.

**Comment by karelzak** [comment]
Merged to the master branch.

**Comment by karelzak** [comment]
Mario, can you create another PR with an update to man-common/README with examples of how to use po4a, how to generate the main .pot file and how to generate the translated adoc files? Please.

**Comment by mariobl** [comment]
Yes, I will do this tonight.

**Pull request closed without merging**
